name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:14

    steps:
      # Checkout actions just downloads code, does not git init
      # Find more info on the bug here - https://github.com/actions/checkout/issues/126
      - uses: actions/checkout@v2

      # Sets up the git repo so that scripts that depend on it will run
      - name: git init
        run: |
          git init
          git add .

      - name: Install dependencies
        run: npm ci

      - name: Config
        run: |
          git config --global user.email "dong23102003@gmail.com"
          git config --global user.name "truongdd03"

      - name: Deploy
        run: npm run deploy
